apiVersion: v2
name: sms-analyzer
description: Enterprise SMS Link Security Analysis Platform
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: redis
    version: 17.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: 12.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

maintainers:
  - name: Net-Zilla Team
    email: cyberzilla.systems@gmail.com
