# Global settings
global:
  environment: production
  domain: analyzer.yourcompany.com

# Application configuration
app:
  replicaCount: 3
  image:
    repository: your-registry/sms-analyzer
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
    metricsPort: 9090
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  livenessProbe:
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 30
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /ready
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 5

# Configuration
config:
  logLevel: "info"
  enableAPI: true
  enableCLI: true
  rateLimit: 100
  analysisTimeout: 30

# Database configuration
database:
  enabled: true
  type: "postgresql"
  host: "postgresql"
  port: 5432
  name: "sms_analyzer"
  username: "analyzer"
  password: ""

# Cache configuration
redis:
  enabled: true
  host: "redis-master"
  port: 6379
  password: ""

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: analyzer.yourcompany.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: sms-analyzer-tls
      hosts:
        - analyzer.yourcompany.com

# Monitoring
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s

# Autoscaling
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
