apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sms-analyzer.fullname" . }}-config
data:
  app.yaml: |
    server:
      host: "0.0.0.0"
      port: {{ .Values.app.service.port }}
      mode: "production"
    
    database:
      driver: "postgres"
      host: "{{ .Values.database.host }}"
      port: {{ .Values.database.port }}
      name: "{{ .Values.database.name }}"
      username: "{{ .Values.database.username }}"
    
    cache:
      type: "redis"
      host: "{{ .Values.redis.host }}"
      port: {{ .Values.redis.port }}
    
    security:
      rate_limit: {{ .Values.config.rateLimit }}
      max_redirects: 10
      timeout: 30
    
    ai:
      enable_ai: true
      confidence_threshold: 0.7
    
    logging:
      level: "{{ .Values.config.logLevel }}"
      format: "json"
