apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sms-analyzer.fullname" . }}
  labels:
    {{- include "sms-analyzer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "sms-analyzer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sms-analyzer.selectorLabels" . | nindent 8 }}
        version: {{ .Values.app.image.tag | default "latest" }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.app.service.port }}
              protocol: TCP
            - name: metrics
              containerPort: {{ .Values.app.service.metricsPort }}
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: "postgres://{{ .Values.database.username }}:{{ .Values.database.password }}@{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
            - name: REDIS_URL
              value: "redis://:{{ .Values.redis.password }}@{{ .Values.redis.host }}:{{ .Values.redis.port }}"
            - name: LOG_LEVEL
              value: {{ .Values.config.logLevel | quote }}
            - name: RATE_LIMIT
              value: {{ .Values.config.rateLimit | quote }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.app.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.app.readinessProbe | nindent 12 }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/configs
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "sms-analyzer.fullname" . }}-config
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
