{{- $fullName := include "sms-analyzer.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-secrets
  labels:
    {{- include "sms-analyzer.labels" . | nindent 4 }}
type: Opaque
data:
  # Database credentials
  {{- if .Values.database.password }}
  database-password: {{ .Values.database.password | b64enc | quote }}
  {{- else }}
  database-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  
  # Redis password
  {{- if .Values.redis.password }}
  redis-password: {{ .Values.redis.password | b64enc | quote }}
  {{- else }}
  redis-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  
  # API Keys for external services
  {{- if .Values.apiKeys.virusTotal }}
  virustotal-api-key: {{ .Values.apiKeys.virusTotal | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.apiKeys.abuseIPDB }}
  abuseipdb-api-key: {{ .Values.apiKeys.abuseIPDB | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.apiKeys.googleSafeBrowsing }}
  google-safebrowsing-api-key: {{ .Values.apiKeys.googleSafeBrowsing | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.apiKeys.ip2Location }}
  ip2location-api-key: {{ .Values.apiKeys.ip2Location | b64enc | quote }}
  {{- end }}
  
  # JWT Secret for API authentication
  jwt-secret: {{ .Values.auth.jwtSecret | default (randAlphaNum 64) | b64enc | quote }}
  
  # Encryption key for sensitive data
  encryption-key: {{ .Values.security.encryptionKey | default (randAlphaNum 32) | b64enc | quote }}

---
# TLS Secret for Ingress (if using cert-manager)
{{- if and .Values.ingress.enabled .Values.ingress.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-tls
  labels:
    {{- include "sms-analyzer.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.tls.crt | b64enc | quote }}
  tls.key: {{ .Values.ingress.tls.key | b64enc | quote }}
{{- end }}

---
# Docker Registry Secret (if using private registry)
{{- if .Values.image.pullSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-pull-secret
  labels:
    {{- include "sms-analyzer.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.image.pullSecret | b64enc | quote }}
{{- end }}
