apiVersion: v1
kind: Service
metadata:
  name: {{ include "sms-analyzer.fullname" . }}
  labels:
    {{- include "sms-analyzer.labels" . | nindent 4 }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.app.service.metricsPort }}"
    prometheus.io/path: "/metrics"
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.app.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "sms-analyzer.selectorLabels" . | nindent 4 }}
